DELETE FROM ana_soggetto;
DELETE FROM ana_atto;
DELETE FROM ot_indice;
DELETE FROM ana_fam;
DELETE FROM edi_pratica;
DELETE FROM pol_veicolo;
DELETE FROM pol_zona_permesso;
DELETE FROM scu_classe;
DELETE FROM scu_istituto;
DELETE FROM sdi_graduatoria;
DELETE FROM sdi_servizio;
DELETE FROM scu_soggetto;
DELETE FROM ser_import;
DELETE FROM ser_export;
DELETE FROM ser_istruttoria;
DELETE FROM ser_transazione;
DELETE FROM pra_pratica_pag;
DELETE FROM pra_pratica_testa;
DELETE FROM esinextid WHERE nome_tabella != 'ESINEXTID';
UPDATE esinextid SET next_id = 1 WHERE nome_tabella = 'ESINEXTID';
